# Generated by Django 4.1.7 on 2023-02-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destnation', models.CharField(max_length=100)),
                ('tripDate', models.DateField(max_length=20)),
                ('bookingDate', models.DateField(max_length=20)),
                ('userName', models.CharField(max_length=100)),
            ],
        ),
    ]
