# Generated by Django 4.1.7 on 2023-03-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
