# Generated by Django 4.1.7 on 2023-03-07 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_bookings_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.bookings')),
            ],
        ),
    ]
