# Generated by Django 4.1.7 on 2023-03-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite_places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('destination', models.CharField(max_length=100)),
                ('time', models.TimeField()),
            ],
        ),
    ]
