# Generated by Django 4.1.7 on 2023-03-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_favorite_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite_places',
            name='quotation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
